import type { SpeciesCard } from '../../types';

/* ---------- Adriatic species library (Phase 14) ----------

   30+ species Ivan, Luka, and any Adriatic fisherman would know by name.
   Croatian-first: dialect variants per island where they meaningfully
   differ. Months/methods follow Croatian small-boat fishing tradition.

   Sources combined:
     • Hektorović 1568 species mentions
     • Croatian Sea Fisheries Institute (HAOP) species lists
     • Folk knowledge from Hvar / Vis / Brač / Korčula traditions
     • IUCN Red List 2024 status

   Status notes intentionally honest — Adriatic stocks of dentex (zubatac)
   and pagrus (pagar) are pressured; tuna stocks recovering since 2010s.

   This is the EMPTY-SHELL Tomo specified — full structure, factual
   biology, ready for Ivan to audit and personalise during the demo trip. */

export const SEED_SPECIES: SpeciesCard[] = [
  /* ---------- Pelagic schooling ---------- */
  {
    id: 'sp-sardela',
    nameCro: 'Sardela',
    nameEng: 'European pilchard',
    scientific: 'Sardina pilchardus',
    category: 'pelagic',
    dialects: [
      { region: 'hvarski', name: 'sardina' },
      { region: 'viški',   name: 'sardelа' },
      { region: 'brački',  name: 'sardelina' },
    ],
    depthRangeM: { min: 25, max: 150 },
    minSizeCm: 11,
    monthsActive: [5, 6, 7, 8, 9],
    bestTimeOfDay: ['night'],
    methods: ['poljanica', 'mreža plivarica', 'lampa'],
    baits: [],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Hektorović\'s archetypal fish — backbone of small-boat economy. Night fishing under lamp light still the dominant method.',
  },
  {
    id: 'sp-incun',
    nameCro: 'Inćun',
    nameEng: 'European anchovy',
    scientific: 'Engraulis encrasicolus',
    category: 'pelagic',
    dialects: [
      { region: 'hvarski',     name: 'inčun' },
      { region: 'dalmatinski', name: 'inćun' },
      { region: 'viški',       name: 'mas' },
    ],
    depthRangeM: { min: 5, max: 200 },
    minSizeCm: 9,
    monthsActive: [4, 5, 6, 7, 8, 9, 10],
    bestTimeOfDay: ['night'],
    methods: ['poljanica', 'mreža plivarica'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Often confused with sardela — distinguishable by underbite and silver lateral stripe.',
  },
  {
    id: 'sp-skusa',
    nameCro: 'Skuša',
    nameEng: 'Atlantic mackerel',
    scientific: 'Scomber scombrus',
    category: 'pelagic',
    dialects: [
      { region: 'hvarski', name: 'skuša' },
      { region: 'viški',   name: 'lokarda' },
    ],
    depthRangeM: { min: 0, max: 200 },
    minSizeCm: 18,
    monthsActive: [6, 7, 8, 9],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula', 'mreža', 'kanjac'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Trolling (panula) at dawn from the boat — iconic Adriatic technique.',
  },
  {
    id: 'sp-lokarda',
    nameCro: 'Lokarda',
    nameEng: 'Atlantic chub mackerel',
    scientific: 'Scomber colias',
    category: 'pelagic',
    depthRangeM: { min: 0, max: 300 },
    monthsActive: [6, 7, 8, 9],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Larger and stockier than skuša. Often caught alongside.',
  },
  {
    id: 'sp-tuna',
    nameCro: 'Tuna',
    nameEng: 'Atlantic bluefin tuna',
    scientific: 'Thunnus thynnus',
    category: 'pelagic',
    dialects: [
      { region: 'dalmatinski', name: 'tunj' },
      { region: 'hvarski',     name: 'tunja' },
    ],
    depthRangeM: { min: 0, max: 500 },
    minSizeCm: 30,
    monthsActive: [6, 7, 8],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula', 'parangal', 'tuna-trap'],
    iucn: 'LC',
    adriaticStock: 'declining',
    notes: 'Strict EU quota. Recovering since 2010s. Croatian tuna farms in Kali / Brijuni dominant.',
  },
  {
    id: 'sp-palamida',
    nameCro: 'Palamida',
    nameEng: 'Atlantic bonito',
    scientific: 'Sarda sarda',
    category: 'pelagic',
    depthRangeM: { min: 0, max: 200 },
    minSizeCm: 25,
    monthsActive: [8, 9, 10, 11],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Late-summer migration through Croatian waters. Trolled with feathers.',
  },
  {
    id: 'sp-iglica',
    nameCro: 'Iglica',
    nameEng: 'Garfish',
    scientific: 'Belone belone',
    category: 'pelagic',
    dialects: [
      { region: 'dalmatinski', name: 'iglica' },
      { region: 'hvarski',     name: 'lin' },
    ],
    depthRangeM: { min: 0, max: 100 },
    monthsActive: [5, 6, 7, 8, 9],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula', 'štap s plovkom'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Distinctive green bones — surprises first-time eaters.',
  },
  {
    id: 'sp-snjur',
    nameCro: 'Šnjur',
    nameEng: 'Atlantic horse mackerel',
    scientific: 'Trachurus trachurus',
    category: 'pelagic',
    depthRangeM: { min: 0, max: 1000 },
    minSizeCm: 12,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula', 'mreža', 'poljanica'],
    iucn: 'VU',
    adriaticStock: 'declining',
    notes: 'Common bait fish AND eating fish. Adriatic stock under pressure from trawling.',
  },
  {
    id: 'sp-gof',
    nameCro: 'Gof',
    nameEng: 'Greater amberjack',
    scientific: 'Seriola dumerili',
    category: 'pelagic',
    depthRangeM: { min: 20, max: 360 },
    minSizeCm: 45,
    monthsActive: [6, 7, 8, 9, 10],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['panula', 'parangal', 'jigging'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Trophy fish around outer islands — Vis, Lastovo, Palagruža.',
  },

  /* ---------- Demersal (bottom) ---------- */
  {
    id: 'sp-brancin',
    nameCro: 'Lubin',
    nameEng: 'European seabass',
    scientific: 'Dicentrarchus labrax',
    category: 'demersal',
    dialects: [
      { region: 'sjeverni',    name: 'brancin' },
      { region: 'dalmatinski', name: 'lubin' },
    ],
    depthRangeM: { min: 10, max: 100 },
    minSizeCm: 25,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['night', 'dawn'],
    methods: ['parangal', 'koža', 'štap'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Year-round. Best at first light or in oily weather. Wild fish far better than farmed.',
  },
  {
    id: 'sp-orada',
    nameCro: 'Orada',
    nameEng: 'Gilthead seabream',
    scientific: 'Sparus aurata',
    category: 'demersal',
    dialects: [
      { region: 'sjeverni',    name: 'komarča' },
      { region: 'dalmatinski', name: 'orada' },
      { region: 'hvarski',     name: 'komarić' },
    ],
    depthRangeM: { min: 1, max: 30 },
    minSizeCm: 20,
    monthsActive: [5, 6, 7, 8, 9, 10],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['parangal', 'štap', 'mreža'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Shallow lagoons and seagrass beds. Distinctive gold spot between eyes.',
  },
  {
    id: 'sp-zubatac',
    nameCro: 'Zubatac',
    nameEng: 'Common dentex',
    scientific: 'Dentex dentex',
    category: 'demersal',
    depthRangeM: { min: 15, max: 200 },
    minSizeCm: 30,
    monthsActive: [4, 5, 6, 7, 8, 9, 10],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['parangal', 'panula', 'štap od dna'],
    iucn: 'VU',
    adriaticStock: 'declining',
    notes: 'Apex Adriatic predator — under pressure. Trophy fish but conservation watch.',
  },
  {
    id: 'sp-pagar',
    nameCro: 'Pagar',
    nameEng: 'Common seabream',
    scientific: 'Pagrus pagrus',
    category: 'demersal',
    depthRangeM: { min: 0, max: 200 },
    minSizeCm: 20,
    monthsActive: [4, 5, 6, 7, 8, 9, 10],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['parangal'],
    iucn: 'VU',
    adriaticStock: 'declining',
    notes: 'Often confused with zubatac. Pinker hue, smaller. Quota-watched.',
  },
  {
    id: 'sp-kovac',
    nameCro: 'Kovač',
    nameEng: 'John Dory',
    scientific: 'Zeus faber',
    category: 'demersal',
    depthRangeM: { min: 5, max: 400 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['parangal', 'vrše', 'koča'],
    iucn: 'DD',
    adriaticStock: 'unknown',
    notes: 'Distinctive thumb-print spot ("St. Peter\'s mark"). Rare prize.',
  },
  {
    id: 'sp-kanjac',
    nameCro: 'Kanjac',
    nameEng: 'Comber',
    scientific: 'Serranus cabrilla',
    category: 'demersal',
    depthRangeM: { min: 5, max: 500 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['vrše', 'kanjci (small hand-line)', 'štap'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'The teaching fish — kids first catch on hand-line. Year-round friend.',
  },
  {
    id: 'sp-trlja',
    nameCro: 'Trlja od kamena',
    nameEng: 'Striped red mullet',
    scientific: 'Mullus surmuletus',
    category: 'demersal',
    depthRangeM: { min: 5, max: 100 },
    minSizeCm: 11,
    monthsActive: [4, 5, 6, 7, 8, 9, 10],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['mreža', 'vrše', 'štap'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Two species in Adriatic — rocky-bottom (od kamena) and muddy-bottom (od mulja). Latter cheaper.',
  },
  {
    id: 'sp-fratar',
    nameCro: 'Fratar',
    nameEng: 'Common two-banded seabream',
    scientific: 'Diplodus vulgaris',
    category: 'demersal',
    depthRangeM: { min: 0, max: 160 },
    minSizeCm: 18,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['štap', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Two black bands. Dependable shore-fish. Inquisitive — easy on hand-line.',
  },
  {
    id: 'sp-sarag',
    nameCro: 'Šarag',
    nameEng: 'Sharpsnout seabream',
    scientific: 'Diplodus puntazzo',
    category: 'demersal',
    dialects: [
      { region: 'hvarski', name: 'piknjavac' },
    ],
    depthRangeM: { min: 0, max: 150 },
    minSizeCm: 18,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['štap', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Pointy snout vs the cousins. Reef-loving.',
  },
  {
    id: 'sp-spar',
    nameCro: 'Špar',
    nameEng: 'Annular seabream',
    scientific: 'Diplodus annularis',
    category: 'demersal',
    depthRangeM: { min: 0, max: 90 },
    minSizeCm: 12,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['štap', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Smallest of the seabream cousins. Shallow seagrass.',
  },
  {
    id: 'sp-bukva',
    nameCro: 'Bukva',
    nameEng: 'Bogue',
    scientific: 'Boops boops',
    category: 'demersal',
    depthRangeM: { min: 0, max: 350 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['parangal', 'mreža', 'štap'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Big golden eye. Fried whole — Croatian harbour-side standard.',
  },
  {
    id: 'sp-gera',
    nameCro: 'Gira',
    nameEng: 'Picarel',
    scientific: 'Spicara smaris',
    category: 'demersal',
    dialects: [
      { region: 'hvarski',     name: 'gera' },
      { region: 'dalmatinski', name: 'gira' },
    ],
    depthRangeM: { min: 15, max: 170 },
    monthsActive: [4, 5, 6, 7, 8, 9],
    bestTimeOfDay: ['all'],
    methods: ['mreža', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'The "small fry" everyone knows. Fried gira + young white wine = summer.',
  },
  {
    id: 'sp-ugor',
    nameCro: 'Ugor',
    nameEng: 'European conger',
    scientific: 'Conger conger',
    category: 'demersal',
    depthRangeM: { min: 100, max: 1000 },
    monthsActive: [9, 10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ['night'],
    methods: ['parangal'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Cold-water predator. Night long-line in winter. Up to 2m+.',
  },
  {
    id: 'sp-murina',
    nameCro: 'Murina',
    nameEng: 'Mediterranean moray',
    scientific: 'Muraena helena',
    category: 'demersal',
    depthRangeM: { min: 5, max: 100 },
    monthsActive: [6, 7, 8, 9, 10],
    bestTimeOfDay: ['dusk', 'night'],
    methods: ['vrše', 'parangal'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Reef-dweller. Bite sharp — Romans famously kept her in pools.',
  },

  /* ---------- Cephalopods ---------- */
  {
    id: 'sp-lignja',
    nameCro: 'Lignja',
    nameEng: 'European squid',
    scientific: 'Loligo vulgaris',
    category: 'cephalopod',
    dialects: [
      { region: 'dalmatinski', name: 'lignja (sing.) · lignje (pl.)' },
    ],
    depthRangeM: { min: 5, max: 500 },
    monthsActive: [9, 10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ['night'],
    methods: ['koža', 'panula sa žaruljom', 'totanara'],
    iucn: 'DD',
    adriaticStock: 'stable',
    notes: 'Best autumn → winter. Squid jig under boat light is ritual on Hvar / Vis.',
  },
  {
    id: 'sp-sipa',
    nameCro: 'Sipa',
    nameEng: 'Common cuttlefish',
    scientific: 'Sepia officinalis',
    category: 'cephalopod',
    depthRangeM: { min: 0, max: 200 },
    monthsActive: [3, 4, 5, 6],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['vrše', 'štap od dna', 'totanara'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Spring spawn in shallow grass. Black-ink risotto comes from her.',
  },
  {
    id: 'sp-hobotnica',
    nameCro: 'Hobotnica',
    nameEng: 'Common octopus',
    scientific: 'Octopus vulgaris',
    category: 'cephalopod',
    depthRangeM: { min: 0, max: 200 },
    minSizeCm: 4,  // weight rule actually 1kg, but stub it
    monthsActive: [9, 10, 11, 12, 1, 2, 3, 4],
    bestTimeOfDay: ['all'],
    methods: ['ručno', 'vrše', 'kuke', 'osti'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Cooler months. Hand-caught from rocks — Hektorović\'s octopus tradition still alive.',
  },
  {
    id: 'sp-muzgavac',
    nameCro: 'Muzgavac',
    nameEng: 'Musky octopus',
    scientific: 'Eledone moschata',
    category: 'cephalopod',
    depthRangeM: { min: 50, max: 500 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['koča', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Smaller cousin of hobotnica. Trawl-caught mainly. Distinct musky note.',
  },

  /* ---------- Crustaceans ---------- */
  {
    id: 'sp-jastog',
    nameCro: 'Jastog',
    nameEng: 'European spiny lobster',
    scientific: 'Palinurus elephas',
    category: 'crustacean',
    depthRangeM: { min: 5, max: 200 },
    minSizeCm: 24,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['night'],
    methods: ['vrše'],
    iucn: 'VU',
    adriaticStock: 'declining',
    notes: 'Quota + size limit + closed season Sep 16–Apr 30 historically. Vulnerable.',
  },
  {
    id: 'sp-hlap',
    nameCro: 'Hlap',
    nameEng: 'European lobster',
    scientific: 'Homarus gammarus',
    category: 'crustacean',
    depthRangeM: { min: 0, max: 150 },
    minSizeCm: 24,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['night'],
    methods: ['vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Big claws — distinct from jastog. Hard rocky bottoms.',
  },
  {
    id: 'sp-skamp',
    nameCro: 'Škamp',
    nameEng: 'Norway lobster · langoustine',
    scientific: 'Nephrops norvegicus',
    category: 'crustacean',
    depthRangeM: { min: 20, max: 800 },
    minSizeCm: 9,
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['dawn', 'dusk'],
    methods: ['koča', 'vrše'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Soft mud bottoms. Kvarner gulf famous. Buzara di scampi — Adriatic gospel.',
  },
  {
    id: 'sp-rakovica',
    nameCro: 'Rakovica',
    nameEng: 'Spinous spider crab',
    scientific: 'Maja squinado',
    category: 'crustacean',
    depthRangeM: { min: 0, max: 90 },
    monthsActive: [11, 12, 1, 2, 3],
    bestTimeOfDay: ['all'],
    methods: ['vrše', 'ručno'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Winter star — meat richest after the December moult.',
  },

  /* ---------- Shellfish ---------- */
  {
    id: 'sp-kamenica',
    nameCro: 'Kamenica',
    nameEng: 'European flat oyster',
    scientific: 'Ostrea edulis',
    category: 'shellfish',
    depthRangeM: { min: 0, max: 80 },
    monthsActive: [9, 10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ['all'],
    methods: ['ručno', 'uzgoj'],
    iucn: 'VU',
    adriaticStock: 'protected',
    notes: 'Ston bay famous. Best in months with R (Croatian: months when "r" appears in the name).',
  },
  {
    id: 'sp-dagnja',
    nameCro: 'Dagnja',
    nameEng: 'Mediterranean mussel',
    scientific: 'Mytilus galloprovincialis',
    category: 'shellfish',
    depthRangeM: { min: 0, max: 40 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['uzgoj', 'ručno'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Ston, Mali Ston, Lim bay famous farms. Strong year-round.',
  },
  {
    id: 'sp-kunjka',
    nameCro: 'Kunjka',
    nameEng: 'Noah\'s ark shell',
    scientific: 'Arca noae',
    category: 'shellfish',
    depthRangeM: { min: 0, max: 40 },
    monthsActive: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bestTimeOfDay: ['all'],
    methods: ['ručno', 'ronjenje'],
    iucn: 'LC',
    adriaticStock: 'stable',
    notes: 'Hand-collected from rocks. Grilled with bread crumbs and garlic — Dalmatinski klasik.',
  },
];
